apiVersion: apps/v1
kind: Deployment
metadata:
  name: people-service
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: people-service
  template:
    metadata:
      labels:
        app: people-service
    spec:
      containers:
        - name: people-service
          image: harbor.plavonra.com/apps/people-service:0.0.2
          # server
          imagePullPolicy: Always
          # local images
#          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: postgres-db-config
            - configMapRef:
                name: ollama-ai-config
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-db-secret
                  key: password
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1"

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8181
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8181
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: people-service
  namespace: apps
spec:
  selector:
    app: people-service
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: people-service
  namespace: apps
  annotations:
    nginx.ingress.kubernetes.io/x-forwarded-prefix: /people-service
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: api.plavonra.com
      http:
        paths:
          - path: /people-service
            pathType: Prefix
            backend:
              service:
                name: people-service
                port:
                  number: 80