management:
  server:
    port: 8181
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
    loggers:
      enabled: true
    threaddump:
      enabled: true
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,loggers,threaddump
spring:
  application:
    name: people-service
  datasource:
    url: ${SPRING_POSTGRES_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_POSTGRES_DATASOURCE_USERNAME:username}
    password: ${SPRING_POSTGRES_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none  # disable Hibernate
  sql:
    init:
      mode: always     # always run scripts
  ai:
    ollama:
      base-url: ${SPRING_AI_OLLAMA_BASE_URL:http://localhost:11436}
      chat:
        options:
          model: gemma3:270m
      embedding:
        options:
          model: nomic-embed-text
    chat:
      observations:
        log-prompt: true
        log-completion: true
    vectorstore:
      pgvector:
        schema-name: person
        table-name: person_note_embedding
        dimensions: 768
        remove-existing-vector-store-table: false
plavonra:
  ai:
    langfuse:
      prompts:
        person-note-analysis-user:
          primary: production
          fallback: staging
        person-note-analysis-system:
          primary: production
          fallback: staging
ai:
  search:
    top-k: 5
    similarity-threshold: 0.55
server:
  servlet.context-path: /${spring.application.name}
  error:
    include-stacktrace: never
    whitelabel:
      enabled: false